#!/usr/bin/env python3
"""Generate CSS custom properties, Tailwind config, and Google Fonts embed links
from a font selection and typographic scale choice."""

import argparse
import csv
import os
import sys
from urllib.parse import quote

SCALES = {
    "minor-second":     1.067,
    "major-second":     1.125,
    "minor-third":      1.200,
    "major-third":      1.250,
    "perfect-fourth":   1.333,
    "augmented-fourth": 1.414,
    "perfect-fifth":    1.500,
    "golden-ratio":     1.618,
}

TIERS = ["xs", "sm", "base", "lg", "xl", "2xl", "3xl", "4xl"]

LINE_HEIGHTS = {
    "xs": 1.6, "sm": 1.6, "base": 1.5, "lg": 1.45,
    "xl": 1.35, "2xl": 1.25, "3xl": 1.15, "4xl": 1.1,
}

LETTER_SPACINGS = {
    "xs": "0.01em", "sm": "0.01em", "base": "0em", "lg": "-0.005em",
    "xl": "-0.01em", "2xl": "-0.015em", "3xl": "-0.02em", "4xl": "-0.025em",
}

MARGIN_BOTTOMS = {
    "xs": "0.5em", "sm": "0.5em", "base": "0.75em", "lg": "1em",
    "xl": "1.25em", "2xl": "1.5em", "3xl": "1.75em", "4xl": "2em",
}


def compute_sizes(base, ratio):
    """Return dict of tier -> rem value."""
    sizes = {}
    powers = {"xs": -2, "sm": -1, "base": 0, "lg": 1, "xl": 2, "2xl": 3, "3xl": 4, "4xl": 5}
    for tier, power in powers.items():
        px = base * (ratio ** power)
        rem = px / base
        sizes[tier] = round(rem, 4)
    return sizes


def lookup_category(font_name, data_dir):
    """Look up font category from data/fonts.csv. Return category string or None."""
    csv_path = os.path.join(data_dir, "data", "fonts.csv")
    if not os.path.isfile(csv_path):
        return None
    try:
        with open(csv_path, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                name_field = row.get("family") or row.get("name") or row.get("Family") or row.get("Name") or ""
                if name_field.strip().lower() == font_name.strip().lower():
                    return row.get("category") or row.get("Category") or None
    except Exception:
        pass
    return None


def get_fallback(font_name, data_dir):
    """Determine CSS fallback stack from font category."""
    cat = lookup_category(font_name, data_dir)
    if cat:
        cat_lower = cat.lower()
        if "serif" in cat_lower and "sans" not in cat_lower:
            return "serif"
        if "sans" in cat_lower:
            return "sans-serif"
        if "mono" in cat_lower:
            return "monospace"
    return "sans-serif"


def encode_font(name):
    """URL-encode font name for Google Fonts (spaces become +)."""
    return name.strip().replace(" ", "+")


def fmt_rem(val):
    """Format rem value, stripping unnecessary trailing zeros."""
    s = f"{val:.4f}".rstrip("0").rstrip(".")
    return s


def generate_css(heading, body, heading_fb, body_fb, sizes, scale_name, ratio, base):
    lines = []
    lines.append("/* Typography System — Generated by auto-google-font */")
    lines.append(f"/* Scale: {scale_name} ({ratio}) | Base: {base}px */")
    lines.append("")
    lines.append(":root {")

    # Font Families
    lines.append("  /* Font Families */")
    if heading and body and heading != body:
        lines.append(f"  --font-heading: '{heading}', {heading_fb};")
        lines.append(f"  --font-body: '{body}', {body_fb};")
    else:
        font = heading or body
        fb = heading_fb or body_fb
        lines.append(f"  --font-body: '{font}', {fb};")
    lines.append("")

    # Font Sizes
    lines.append("  /* Font Sizes */")
    for tier in TIERS:
        lines.append(f"  --font-size-{tier}: {fmt_rem(sizes[tier])}rem;")
    lines.append("")

    # Line Heights
    lines.append("  /* Line Heights */")
    for tier in TIERS:
        lines.append(f"  --line-height-{tier}: {LINE_HEIGHTS[tier]};")
    lines.append("")

    # Letter Spacing
    lines.append("  /* Letter Spacing */")
    for tier in TIERS:
        lines.append(f"  --letter-spacing-{tier}: {LETTER_SPACINGS[tier]};")
    lines.append("")

    # Measure
    lines.append("  /* Measure */")
    lines.append("  --measure-narrow: 45ch;")
    lines.append("  --measure-base: 65ch;")
    lines.append("  --measure-wide: 75ch;")

    lines.append("}")
    return "\n".join(lines)


def generate_tailwind(heading, body, heading_fb, body_fb, sizes, scale_name, ratio, base):
    lines = []
    lines.append("// tailwind.config.js extension")
    lines.append(f"// Scale: {scale_name} ({ratio}) | Base: {base}px")
    lines.append("module.exports = {")
    lines.append("  theme: {")
    lines.append("    extend: {")

    # fontFamily
    lines.append("      fontFamily: {")
    if heading and body and heading != body:
        lines.append(f"        heading: ['{heading}', '{heading_fb}'],")
        lines.append(f"        body: ['{body}', '{body_fb}'],")
    else:
        font = heading or body
        fb = heading_fb or body_fb
        lines.append(f"        body: ['{font}', '{fb}'],")
    lines.append("      },")

    # fontSize
    lines.append("      fontSize: {")
    for tier in TIERS:
        ls = LETTER_SPACINGS[tier]
        lh = str(LINE_HEIGHTS[tier])
        lines.append(f"        '{tier}': ['{fmt_rem(sizes[tier])}rem', {{ lineHeight: '{lh}', letterSpacing: '{ls}' }}],")
    lines.append("      },")

    lines.append("    },")
    lines.append("  },")
    lines.append("}")
    return "\n".join(lines)


def generate_embed(heading, body, heading_weights, body_weights):
    lines = []
    lines.append('<link rel="preconnect" href="https://fonts.googleapis.com">')
    lines.append('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>')

    families = []
    if heading:
        families.append(f"family={encode_font(heading)}:wght@{heading_weights}")
    if body and body != heading:
        families.append(f"family={encode_font(body)}:wght@{body_weights}")

    url = "https://fonts.googleapis.com/css2?" + "&".join(families) + "&display=swap"
    lines.append(f'<link href="{url}" rel="stylesheet">')
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate typography CSS, Tailwind config, and Google Fonts embed links."
    )

    font_group = parser.add_mutually_exclusive_group(required=True)
    font_group.add_argument("--font", help="Single font family (mutually exclusive with --heading/--body)")
    font_group.add_argument("--heading", help="Heading font family name")

    parser.add_argument("--body", help="Body font family name")
    parser.add_argument("--heading-weights", default="400,700", help="Weights for heading (default: 400,700)")
    parser.add_argument("--body-weights", default="300,400,500,600,700", help="Weights for body (default: 300,400,500,600,700)")
    parser.add_argument("--scale", default="major-third", choices=SCALES.keys(), help="Typographic scale (default: major-third)")
    parser.add_argument("--base", type=int, default=16, help="Base font size in px (default: 16)")
    parser.add_argument("--format", default="all", choices=["css", "tailwind", "embed", "all"], help="Output format (default: all)")

    args = parser.parse_args()

    # Resolve font names
    if args.font:
        heading = args.font
        body = args.font
        heading_weights = args.heading_weights
        body_weights = args.body_weights
    else:
        heading = args.heading
        body = args.body
        if not body:
            parser.error("--body is required when using --heading")
        heading_weights = args.heading_weights
        body_weights = args.body_weights

    ratio = SCALES[args.scale]
    sizes = compute_sizes(args.base, ratio)

    # Determine project root (one level up from scripts/)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.dirname(script_dir)

    heading_fb = get_fallback(heading, data_dir)
    body_fb = get_fallback(body, data_dir) if body != heading else heading_fb

    outputs = []

    if args.format in ("css", "all"):
        outputs.append(generate_css(
            heading, body, heading_fb, body_fb,
            sizes, args.scale, ratio, args.base
        ))

    if args.format in ("tailwind", "all"):
        outputs.append(generate_tailwind(
            heading, body, heading_fb, body_fb,
            sizes, args.scale, ratio, args.base
        ))

    if args.format in ("embed", "all"):
        outputs.append(generate_embed(heading, body, heading_weights, body_weights))

    print("\n\n".join(outputs))


if __name__ == "__main__":
    main()
